version: "2"
services:
  phoenix:
    container_name: hust_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      PG_HOST: hust-postgres
    env_file: .dev.env
    ports:
      - "9000:4000"
    volumes:
      - .:/app
    links:
      - hust-postgres
    depends_on:
      - hust-postgres
  hust-postgres:
    image: postgres:9.6.5-alpine
    container_name: hust-postgres
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hust_global_db
      PGDATA: /data/pgdata
    volumes:
      - ./data:/data:cached
    networks:
      - default
